// gallery.js
// 負責從後端取得歷史作品清單，並產生 SVG 預覽與下載按鈕（SVG / STL / G-code）

function downloadFile(content, fileName, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
}

// 與 app.js 相同邏輯：依 paths + drawingBBox 產生 G-code，並用 scale 做 best fit
function generateGCodeFromPaths(paths, drawingBBox, options = {}) {
    const {
        targetSizeMM = 80,
        numLayers = 5,
        layerThickness = 0.2
    } = options;

    if (!drawingBBox) return '';

    const designMax = Math.max(drawingBBox.w, drawingBBox.h) || 1;
    const scale = targetSizeMM / designMax;

    let gcode = "; G-code generated by Drawsth3D\n";
    gcode += "G21 ; 設定單位為毫米(mm)\n";
    gcode += "G90 ; 使用絕對座標\n";
    gcode += "G28 ; 原點復位\n";

    for (let layer = 1; layer <= numLayers; layer++) {
        let currentZ = (layer * layerThickness).toFixed(2);
        gcode += `\n; === 準備列印第 ${layer} 層 (Z=${currentZ}mm) ===\n`;
        gcode += `G1 Z${(parseFloat(currentZ) + 2.0).toFixed(2)} F5000 ; 稍微抬起噴頭移動\n`;

        paths.forEach((path, index) => {
            if (!path.points || path.points.length < 2) return;
            gcode += `; -- 繪製筆畫 ${index + 1} --\n`;

            const startX = ((path.points[0].x - drawingBBox.x) * scale).toFixed(2);
            const startY = ((drawingBBox.y + drawingBBox.h - path.points[0].y) * scale).toFixed(2);

            gcode += `G1 X${startX} Y${startY} F5000\n`;
            gcode += `G1 Z${currentZ} F1000 ; 放下噴頭\n`;

            path.points.forEach(p => {
                const x = ((p.x - drawingBBox.x) * scale).toFixed(2);
                const y = ((drawingBBox.y + drawingBBox.h - p.y) * scale).toFixed(2);
                gcode += `G1 X${x} Y${y} E0.05 F1500\n`;
            });
            gcode += `G1 Z${(parseFloat(currentZ) + 2.0).toFixed(2)} F5000 ; 抬起噴頭\n\n`;
        });
    }

    gcode += "M104 S0 ; 關閉擠出機加熱\n";
    gcode += "M140 S0 ; 關閉熱床\n";
    gcode += "M84 ; 關閉步進馬達\n";

    return gcode;
}

async function loadGallery() {
    const container = document.getElementById('gallery-list');
    container.innerHTML = '<p class="text-center text-muted">載入中...</p>';

    try {
        const res = await fetch('fetch_designs_detail.php');
        if (!res.ok) throw new Error('無法取得作品清單');
        const designs = await res.json();

        if (!designs || designs.length === 0) {
            container.innerHTML = '<p class="text-center text-muted">目前伺服器中沒有任何已上傳的作品。</p>';
            return;
        }

        container.innerHTML = '';

        designs.forEach(design => {
            const col = document.createElement('div');
            col.className = 'col-12 col-md-6 col-lg-4';

            const card = document.createElement('div');
            card.className = 'card h-100 shadow-sm gallery-card';

            // SVG 預覽區
            const previewWrapper = document.createElement('div');
            previewWrapper.className = 'gallery-preview p-3 d-flex justify-content-center align-items-center';

            if (design.svg) {
                const img = document.createElement('img');
                img.src = design.svg;
                img.alt = design.id;
                img.className = 'img-fluid';
                previewWrapper.appendChild(img);
            } else {
                const placeholder = document.createElement('div');
                placeholder.className = 'text-muted';
                placeholder.innerText = '（此作品沒有 SVG 預覽）';
                previewWrapper.appendChild(placeholder);
            }

            const cardBody = document.createElement('div');
            cardBody.className = 'card-body d-flex flex-column';

            const title = document.createElement('h6');
            title.className = 'card-title text-primary fw-bold';
            title.innerText = design.designName || design.id;

            const timeP = document.createElement('p');
            timeP.className = 'card-text text-muted mb-3';
            if (design.mtime) {
                const date = new Date(design.mtime * 1000);
                timeP.innerText = '最後更新：' + date.toLocaleString();
            }

            const btnGroup = document.createElement('div');
            btnGroup.className = 'mt-auto d-flex flex-wrap gap-2';

            if (design.svg) {
                const svgBtn = document.createElement('a');
                svgBtn.href = design.svg;
                svgBtn.download = design.id + '.svg';
                svgBtn.className = 'btn btn-sm btn-outline-primary';
                svgBtn.innerText = '下載 SVG';
                btnGroup.appendChild(svgBtn);
            }

            if (design.stl) {
                const stlBtn = document.createElement('a');
                stlBtn.href = design.stl;
                stlBtn.download = design.id + '.stl';
                stlBtn.className = 'btn btn-sm btn-outline-primary';
                stlBtn.innerText = '下載 STL';
                btnGroup.appendChild(stlBtn);
            }

            if (design.json) {
                const gcodeBtn = document.createElement('button');
                gcodeBtn.type = 'button';
                gcodeBtn.className = 'btn btn-sm btn-primary';
                gcodeBtn.innerText = '下載 G-code';
                gcodeBtn.addEventListener('click', async () => {
                    try {
                        const resJson = await fetch(design.json);
                        if (!resJson.ok) throw new Error('無法讀取 JSON 資料');
                        const data = await resJson.json();
                        const gcode = generateGCodeFromPaths(data.paths || [], data.drawingBBox);
                        if (!gcode) {
                            alert('目前無法產生 G-code，請確認作品 JSON 是否完整。');
                            return;
                        }
                        downloadFile(gcode, design.id + '.gcode', 'text/plain');
                    } catch (err) {
                        alert('產生 G-code 失敗：' + err.message);
                    }
                });
                btnGroup.appendChild(gcodeBtn);
            }

            cardBody.appendChild(title);
            cardBody.appendChild(timeP);
            cardBody.appendChild(btnGroup);

            card.appendChild(previewWrapper);
            card.appendChild(cardBody);

            col.appendChild(card);
            container.appendChild(col);
        });
    } catch (err) {
        container.innerHTML = '<p class="text-center text-danger">載入作品清單時發生錯誤：' + err.message + '</p>';
    }
}

document.addEventListener('DOMContentLoaded', loadGallery);

